name: bom
description: byte order mark (BOM) detection
version: 1.1.0
homepage: https://github.com/Ampless/bom

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
  #tested: ^1.0.0-alpha.2
